#ifndef _DEFINE_CONST_H
#define _DEFINE_CONST_H

#define code_version 11

//-------------------------------------------COU_TIMER

#define def_num_tbrc_s1 2
#define def_num_tbr_g1 3
#define def_num_tb_g2 2

#define def_tbrc_s1_log_root 1

#define def_tbr_g1_DEGUG 1 
#define def_tbr_g1_led_blank 2

#define def_tb_g2_rx_CLR 1

//-------------------------------------------LAYER
#define def_num_led_layer 1

//-------------------------------------------UART
#define def_time_uart_rx_CLR 100
#define def_num_rx_get 20
#define def_num_tx_send 20

#endif

